version: '3.8'

services:
  service1:
    build: ./service1
    ports:
      - "3001:3001"
    networks:
      - ms-net

  service2:
    build: ./service2
    ports:
      - "3002:3002"
    networks:
      - ms-net

networks:
  ms-net:
